server:
  port: 8084
  servlet:
    context-path: /

jwt:
  signerKey : "cNXtAlDGLkUAYwQGg25BZzDm+YrV2MuO4halw14ucMD6tD4aE+laaFujVv4vk/SZJKMNMktf0rJB+F2al3bMFw=="
  signerKey_refresh : "bF6vWkU+8xvZcKkZ+u3sP1xYdI9wA2mQ0aH5jOqF9nJvL1sR0tQfH2y8KpZtVmBxX7o4YdPeL1wT3jK8vH9uJg=="
  token-time : 300 #MIN
  refresh-token-time : 30  #DAY

spring:
  application:
    name: lkdt
  datasource:
    url: jdbc:postgresql://100.114.136.16:5433/postgres
    driverClassName: org.postgresql.Driver
    password: laodaicaha
    username: supabase_admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false