server:
  port: 8084
  servlet:
    context-path: /

jwt:
  signerKey : "cNXtAlDGLkUAYwQGg25BZzDm+YrV2MuO4halw14ucMD6tD4aE+laaFujVv4vk/SZJKMNMktf0rJB+F2al3bMFw=="
  signerKey_refresh : "bF6vWkU+8xvZcKkZ+u3sP1xYdI9wA2mQ0aH5jOqF9nJvL1sR0tQfH2y8KpZtVmBxX7o4YdPeL1wT3jK8vH9uJg=="
  token-time : 300 #MIN
  refresh-token-time : 30  #DAY

spring:
  application:
    name: lkdt
  datasource:
    url: jdbc:postgresql://100.114.136.16:5433/postgres
    driverClassName: org.postgresql.Driver
    password: laodaicaha
    username: supabase_admin
  jpa:
    hibernate:
      ddl-auto: update
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME:dlfnluzp0}
  api_key: ${CLOUDINARY_API_KEY:772959174448354}
  api_secret: ${CLOUDINARY_API_SECRET:MhnxRjkGra60LhTFKXWHtUojaT8}
  upload_folder: ${CLOUDINARY_UPLOAD_FOLDER:thanhcom-uploads}

brevo:
  api-key: ${BREVO_API_KEY}
  sender:
    email: ${BREVO_SENDER_EMAIL}
    name: ${BREVO_SENDER_NAME}
  host: http://localhost:3000
