server:
  port: 8084
  servlet:
    context-path: /
jwt:
  signerKey: ${JWT_SIGNER_KEY}
  signerKey_refresh: ${JWT_SIGNER_KEY_REFRESH}
  token-time: ${JWT_TOKEN_TIME:300}           # default 300 phút
  refresh-token-time: ${JWT_REFRESH_TOKEN_TIME:30} # default 30 ngày
spring:
  application:
    name: lkdt
  datasource:
    url: ${DB_URL:jdbc:postgresql://100.114.136.16:5433/postgres}
    driverClassName: org.postgresql.Driver
    password: ${DB_PASSWORD:supabase_admin}
    username: ${DB_USERNAME:laodaicaha}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false